spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/my-home?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hidden-method:
      filter:
        enabled: true
  #  sql:
  #    init:
  #        mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#cloudinary:
#  cloudinary: ${CLOUDINARY_URL}
#   api-key: ${API_KEY}
#    api-secret: ${API_SECRET}
#      cloud-name: dipiksmcm

mail:
  myHome: "office@myhome.now"
  host: localhost
  port: 1025
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG